import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
const read = (p: string) => readFileSync(p, "utf8")
const page = read("app/academy/[handle]/page.tsx")
const query = read("src/features/academies/queries/get-public-academy-page.ts")
const classes = read("src/features/academies/queries/get-public-academy-classes.ts")
const css = read("app/academy/[handle]/page.module.css")
assert(!query.includes("contact_phone"))
assert(query.includes("phone: toNullableText(organization.academy_phone)"))
assert(query.includes("fetchAcademyPublicProfileBySlug(normalizedHandle)"))
assert(query.includes("isUuid(normalizedHandle)"))
assert(classes.includes('.eq("is_active", true)'))
assert(classes.includes('.neq("booking_status", "hidden")'))
assert(page.includes('src={academy.coverImageUrl}') && page.includes('src={academy.logoImageUrl}'))
assert(page.includes('!academy.coverImageUrl ?'))
assert(page.includes('academy.description ?'))
assert(page.includes('academy.phone ?'))
assert(page.includes('href={`/classes/${item.id}`}'))
assert(page.includes('현재 공개된 수업이 없어요.'))
assert(!page.includes('ParentBottomNav') && !page.includes('mobileCta'))
assert(!css.includes('gradient') && !css.includes('position: fixed'))
assert(read("app/academy/[handle]/error.tsx").includes("router.refresh(); reset()"))
assert(read("app/academy/[handle]/not-found.tsx").includes('href="/academies"'))
assert(read("app/academy/[handle]/loading.tsx").includes('aria-busy="true"'))
console.log("PASS: public phone boundary, slug/UUID, active/hidden contract, actual images, conditional content, states and navigation")
