import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { decisionDraftError, emptyExperienceDecision } from "../src/features/feedback/lib/experience-submission"
const draft = emptyExperienceDecision()
assert(decisionDraftError(draft))
assert.equal(decisionDraftError({ ...draft, decision: "planned" }), null)
assert.equal(decisionDraftError({ ...draft, decision: "considering" }), null)
assert(decisionDraftError({ ...draft, decision: "declined" }))
assert.equal(decisionDraftError({ ...draft, decision: "declined", declineReason: "price" }), null)
const schedule = { ...draft, decision: "declined" as const, declineReason: "schedule_mismatch" as const }
assert(decisionDraftError(schedule))
assert(decisionDraftError({ ...schedule, preferredDays: ["tue"] }))
assert.equal(decisionDraftError({ ...schedule, preferredDays: ["tue"], preferredStartTime: "16:00" }), null)
assert(decisionDraftError({ ...schedule, preferredDays: ["tue"], preferredStartTime: "25:00" }))
assert(decisionDraftError({ ...schedule, preferredDays: ["tue"], preferredStartTime: "16:00", preferredTimeMode: "range", preferredEndTime: "15:00" }))
assert.equal(decisionDraftError({ ...schedule, preferredDays: ["tue"], preferredStartTime: "16:00", preferredTimeMode: "range", preferredEndTime: "18:00" }), null)
const read = (p: string) => readFileSync(p, "utf8")
const action = read("src/features/feedback/actions/save-parent-feedback.ts")
assert.equal((action.match(/await dataAdapter.submitParentExperience/g) ?? []).length, 1)
assert(!action.includes("saveParentExperienceFeedback(")); assert(!action.includes("setParentDecision("))
const ui = read("src/features/feedback/ui/parent-feedback-form.tsx")
assert.equal((ui.match(/type="submit"/g) ?? []).length, 1)
assert(ui.indexOf('type="submit"') > ui.indexOf("<ParentDecisionForm"))
for (const label of ["수정하기", "수정한 피드백 보내기", "생각 변경하기"]) assert(!ui.includes(label))
const sql = read("supabase/migrations/20260929092000_finalize_parent_experience_submission.sql")
assert(sql.includes("for update")); assert(sql.includes("feedback_already_submitted")); assert(!sql.includes("on conflict"))
assert(sql.includes("p_selected_chip_ids is not null or p_private_note is not null"))
assert(sql.includes("feedback_existing_decision_readonly"))
assert(sql.indexOf("insert into public.experience_feedback") < sql.indexOf("perform public.set_parent_decision_internal"))
console.log("PASS final submission validation, one action/CTA, immutable compatibility, transaction/lock boundaries")
