import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { validateChildProfileForm } from "@/features/children/lib/child-form"
import { getChildGradeLabel, normalizeLearnerGrade } from "@/shared/constants/education-taxonomy"
import { resolveParentNavTab } from "@/features/classes/lib/parent-nav"
const read = (p: string) => readFileSync(p, "utf8")
const form = (name: string, grade: string) => { const f = new FormData(); f.set("name", name); f.set("grade", grade); return f }
assert.equal(validateChildProfileForm(form("김시우", "elem_4")).ok, true)
assert.equal(validateChildProfileForm(form("김", "elem_4")).ok, false)
assert.equal(validateChildProfileForm(form("김시우", "invalid")).ok, false)
assert.equal(getChildGradeLabel(normalizeLearnerGrade("elem_4")), "초4")
const values = form("김시우", "elem_4")
for (const field of ["schoolName", "notes", "currentLevel", "interestSubjects", "goalNote"]) values.set(field, ` ${field} `)
const result = validateChildProfileForm(values)
assert(result.ok)
assert.equal(result.input.notes, "notes")
assert.equal(result.input.interestSubjects, "interestSubjects")
assert.equal(resolveParentNavTab("/my/children"), "my")
const ui = read("src/features/children/ui/my-children-manager.tsx")
const client = read("src/features/children/ui/my-children-client.tsx")
const frame = read("src/features/children/ui/children-frame.tsx")
assert(frame.includes('href="/my"'))
assert(frame.includes('data-parent-design="v1"'))
assert(frame.includes('<ParentBottomNav designVersion="v1"'))
assert(ui.includes('getChildGradeLabel(grade)'))
assert(!ui.includes('{item.grade}'))
for (const field of ["notes", "goalNote", "currentLevel", "interestSubjects"]) assert(!ui.includes(`item.${field}`))
assert(ui.includes('scrollIntoView'))
assert(ui.includes('prefers-reduced-motion'))
assert(ui.includes('child-editor-${item.id}'))
assert(!ui.includes('useSearchParams'))
assert(client.includes('onClick={() => void loadChildren()}'))
assert(client.includes('.eq("parent_id", user.id)'))
assert(client.includes('.order("created_at", { ascending: false })'))
assert(read("src/features/children/actions/update-child-profile.ts").includes('parentId: profile.id'))
assert(!ui.includes('삭제'))
assert(read("app/my/children/loading.tsx").includes('<ChildrenFrame><ChildrenSkeleton'))
assert(read("app/my/children/error.tsx").includes('onClick={reset}'))
console.log("PASS: Children fields, validation, grade labels, ownership, ordering, inline edit, retry, context separation and frame")
