import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { FEEDBACK_CHIPS, feedbackChipsForProgram, isFeedbackProgramType, summarizeFeedback, validateFeedbackInput, type FeedbackAggregateSource, type FeedbackChipId } from "../src/features/feedback/lib/experience-feedback"
import { decodePublicFeedback } from "../src/features/feedback/lib/feedback-decode"
assert.equal(FEEDBACK_CHIPS.length,18)
assert.equal(feedbackChipsForProgram("level_test").length,14)
assert(!isFeedbackProgramType("unknown"))
assert.equal(validateFeedbackInput("trial_class",[],"의견만"),null)
assert(validateFeedbackInput("trial_class",[]," \n "))
assert(validateFeedbackInput("trial_class",["child_enjoyed","child_enjoyed"],null))
assert(validateFeedbackInput("level_test",["child_focused"],null))
const row=(a:string,p:string,ids:FeedbackChipId[]):FeedbackAggregateSource=>({applicationId:a,parentId:p,selectedChipIds:ids})
const rows=[row("a","a",["child_enjoyed","kind_teacher","clean_facilities"]),row("b","b",["child_enjoyed","kind_teacher","clean_facilities"]),row("c","c",["child_enjoyed","kind_teacher","clean_facilities"])]
assert.deepEqual(summarizeFeedback(rows.slice(0,2),"CLASS"),{chips:[]})
assert.deepEqual(summarizeFeedback(rows.map(r=>({...r,parentId:"same"})),"CLASS"),{chips:[]})
assert.deepEqual(summarizeFeedback(rows,"CLASS"),{chips:[{id:"child_enjoyed",count:3},{id:"kind_teacher",count:3}]})
assert.deepEqual(summarizeFeedback(rows,"ACADEMY"),{chips:[{id:"kind_teacher",count:3},{id:"clean_facilities",count:3}]})
assert.equal(summarizeFeedback([...rows,row("d","a",["child_enjoyed"])],"CLASS").chips[0].count,4)
assert.deepEqual(summarizeFeedback([...rows.slice(0,2),row("note","c",[])],"CLASS"),{chips:[]})
const all=rows.map(r=>({...r,selectedChipIds:FEEDBACK_CHIPS.map(c=>c.id)}))
assert.equal(summarizeFeedback(all,"CLASS").chips.length,6)
assert.deepEqual(decodePublicFeedback({chips:[{id:"child_enjoyed",count:3,private_note:"SECRET",parent_id:"SECRET"}],private_note:"SECRET"}),{chips:[{id:"child_enjoyed",count:3}]})
assert.throws(()=>decodePublicFeedback({chips:[{id:"child_enjoyed",count:2}]}))
const sql=readFileSync("supabase/migrations/20260929091000_parent_experience_feedback.sql","utf8")
for(const [index,chip] of FEEDBACK_CHIPS.entries()) assert(sql.includes(`('${chip.id}','${chip.scope}',${index+1},`),`SQL taxonomy drift: ${chip.id}`)
const publicQuery=readFileSync("src/features/feedback/queries/get-public-feedback.ts","utf8")
assert(!/privateNote|private_note|service.role|experience_feedback"/.test(publicQuery))
const publicUi=readFileSync("src/features/feedback/ui/public-feedback.tsx","utf8")
assert(!/privateNote|private_note|parentId|applicationId|AggregateRating|ratingValue/.test(publicUi))
const form=readFileSync("src/features/feedback/ui/parent-feedback-form.tsx","utf8")
assert(form.includes('aria-pressed=')&&form.includes('disabled=')&&form.includes('aria-busy='))
const action=readFileSync("src/features/feedback/actions/save-parent-feedback.ts","utf8")
assert(action.includes('requireParentAccess')&&!action.includes('console.'))
console.log('PASS feedback taxonomy, validators, privacy thresholds, scope, top six/tie order, safe decoding, action/UI boundaries')
