import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { resolveParentNavTab } from "@/features/classes/lib/parent-nav"
const read = (path: string) => readFileSync(path, "utf8")
const page = read("app/my/page.tsx")
const frame = read("app/my/my-frame.tsx")
const hub = read("src/features/my/ui/my-hub.tsx")
assert.equal(resolveParentNavTab("/my"), "my")
assert.equal(resolveParentNavTab("/my/children"), "my")
assert.equal(resolveParentNavTab("/my/schedule"), "schedule")
assert(page.includes('requireParentAccess({ returnTo })') && page.includes('withParentChild('))
assert(page.includes('childrenCount={children.error ? null : children.data.length}'))
assert(!page.includes("getMyDashboard"))
assert(hub.includes('childrenCount !== null'))
assert(hub.includes('childrenError ?'))
assert(hub.includes('<MyRetry />'))
assert(read('src/features/my/ui/my-retry.tsx').includes('router.refresh()'))
assert(hub.includes('method="post" action="/auth/sign-out"'))
for (const route of ['/my/children','/my/applications','/favorites','/terms','/privacy','/third-party-consent']) assert(hub.includes(`href="${route}"`))
for (const route of ['/my/schedule','/record','/my/actions']) assert(!hub.includes(`href="${route}"`))
assert(hub.includes('<ParentProfileForm') && hub.includes('<ParentAccountSheet') && hub.includes('onClick={openEditor}'))
assert(hub.includes('<ParentAccountDeletion'))
assert(frame.includes('href="/notifications"'))
assert(frame.includes('data-parent-design="v1"'))
assert(frame.includes('<ParentAppShell') && frame.includes('<ParentHeader'))
assert(page.includes('<ParentFooter showLegalLinks={false} designVersion="v1"'))
assert(read('src/features/classes/ui/parent-footer.tsx').includes('showLegalLinks = true'))
assert(read('app/my/loading.tsx').includes('aria-busy="true"'))
assert(read('app/my/error.tsx').includes('window.location.reload()'))
console.log('PASS: My navigation, real routes, child error isolation, retry, Footer opt-in, existing account sheets, loading/error')
